Halt script on error.

diff --git a/bootstrap-linux b/bootstrap-linux
--- a/bootstrap-linux
+++ b/bootstrap-linux
@@ -11,6 +11,9 @@
 puppet_default_vers=3.4.2-1puppetlabs1
 release_default=precise
 
+# Stop on error:
+set -e
+
 function usage {
     echo "Usage: $0 [-d puppet_version] -n fqdn [-s] [-p puppetmasterFQDN [-i puppetmasterIP]] [-r release]"
     echo "Usage: $0 -h"
